### ISSUE TITLE
Issue when deleting a folder

### ISSUE THREAD

**Issue by jbonney** [fman-community/fman#341]
Hi,
When trying to delete a folder from my [keybase](https://keybase.io/) folder on Linux, an error occurs. See screenshot below for more information.
![selection_005](https://user-images.githubusercontent.com/1498014/37541503-27f08288-295b-11e8-8f46-ba5a4df71dc2.jpg)
Let me know if you need additional information.

**Comment by mherrmann** [comment]
Hi Jimmy, which distribution are you on and which DE are you using?

**Comment by jbonney** [comment]
Hi Michael, I am using elementary OS 0.4.1 Loki (Built on "Ubuntu 16.04.3 LTS"). The DE is Pantheon. Let me know if you need more information.

**Comment by mherrmann** [comment]
Hi Jimmy, does deleting other files work?

**Comment by jbonney** [comment]
Hi Michael, there are no issues to delete other files.

**Comment by mherrmann** [comment]
I've implemented an attempt at a fix. Will go live with 0.9.9. I'd ask that you please test once it's out and let me know whether it works. I'll let you know here when it's ready.

**Comment by mherrmann** [comment]
[fman 0.9.9](https://fman.io/changelog#v0.9.9) is out. Can you [update](https://fman.io/docs/automatic-updates) and let me know whether it works for you?

**Comment by jbonney** [comment]
Hi Michael, there is no more backtrace when trying to delete so the fix worked. I have however opened another issue (#381) since deleting the folder still doesn't work.
