### ISSUE TITLE
fman doesn't work on Fedora 30

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#654]
fman installed from repository (as per instructions on fman.io website) doesn't work on recently released Fedora 30. Here's the error message:
> Traceback (most recent call last):
  File "fman/main.py", line 21, in <module>
  File "fman/main.py", line 4, in main
  File "/root/fman/venv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "fman/impl/application_context.py", line 10, in <module>
  File "/root/fman/venv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "fman/impl/metrics.py", line 7, in <module>
  File "/root/fman/venv/lib64/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "ssl.py", line 101, in <module>
ImportError: libssl.so.10: cannot open shared object file: No such file or directory
[3018] Failed to execute script main

**Comment by drodben** [comment]
Hi, install **compat-openssl10** did the trick for me in Fedora 30:
`dnf install compat-openssl10.x86_64`

**Comment by mherrmann** [comment]
Thank you for sharing `drodben`. Would the problem also be solved by installing `compat-openssl10` instead of `compat-openssl10.x86_64`?

**Comment by drodben** [comment]
Hi again... I guess yes, as `compat-openssl10` provides `libssl.so.10`... the _x86_64_ is not needed actually.
Re-checked again in my system and seems to work the same.

**Comment by mherrmann** [comment]
Thanks! I now changed it so fman declares `compat-openssl10` as a dependency. This should fix the problem out of the box on Fedora 30.
(The reason I used `compat-openssl10` and not `compat-openssl10.x86_64` is that the latter is not available on Fedora 29.)

**Comment by laurent-indermuehle** [comment]
The problem came back on Fedora 31 (not tested Fedora 32)
 Installing compat-openssl10 manually fixed the issue.

**Comment by joshas** [comment]
Same issue on Fedora 32. Tested on Live CD to be sure that system is clean. Installing compat-openssl10 manually fixed the issue.

**Comment by mherrmann** [comment]
I'm surprised you are mentioning this @Honiix and @joshas. The "Thank You" page that you get to when you click "Download" on fman.io says:

![image](https://user-images.githubusercontent.com/1076393/84172192-0254cd00-aa7c-11ea-8f45-3de6702be816.png)

I'll update this to say "Fedora 30+".

**Comment by joshas** [comment]
Sorry, I presumed "_fman declares compat-openssl10 as a dependency_" meant that it will be installed automatically.

**Comment by mherrmann** [comment]
Ah, I see, sorry. It did, briefly. (See the [release notes for version 1.6.2](https://fman.io/changelog#v1.6.2)). But that broke CentOS. So I reverted the change and instead updated the Download page to say that, if you are on Fedora, you need to install `compat-openssl10`.
